import { createGlobalTheme, createThemeContract } from '@vanilla-extract/css';

export const bluePrint = createThemeContract({
  color: {
    neutral1: null,
    neutral2: null,
    neutral3: null,
    neutral4: null,
    neutral5: null,
    neutral6: null,
    neutral7: null,
    neutral8: null,
    peach1: null,
    red1: null,
    brown1: null,
    yellow1: null,
    orange1: null,
    olive1: null,
    green1: null,
    teal1: null,
    navy1: null,
    cobalt1: null,
    blue1: null,
    perwinkle1: null,
    violet1: null,
    magenta1: null,
    purple1: null,
    peach2: null,
    red2: null,
    brown2: null,
    yellow2: null,
    orange2: null,
    olive2: null,
    green2: null,
    teal2: null,
    navy2: null,
    cobalt2: null,
    blue2: null,
    perwinkle2: null,
    violet2: null,
    magenta2: null,
    purple2: null,
    peach3: null,
    red3: null,
    brown3: null,
    yellow3: null,
    orange3: null,
    olive3: null,
    green3: null,
    teal3: null,
    navy3: null,
    cobalt3: null,
    blue3: null,
    perwinkle3: null,
    violet3: null,
    magenta3: null,
    purple3: null,
  },
});

export const globalTheme = createGlobalTheme(`html`, {
  family: {
    mono: `monospace`,
    sans: `'Montserrat',system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif`,
  },
  fontWeights: {
    normal: `400`,
    bold: `700`,
    black: `900`,
  },
  fontSizes: {
    xsmall: `11px`,
    smallest: `12px`,
    smaller: `13px`,
    small: `14px`,
    regular: `16px`,
    large: `18px`,
    larger: `20px`,
    largest: `24px`,
    xlarge: `28px`,
    xxlarge: `32px`,
  },
  radii: {
    none: `0px`,
    xxs: `2px`,
    xs: `4px`,
    sm: `6px`,
    lg: `16px`,
  },
  space: {
    none: `0px`,
    xsmall: `2px`,
    smallest: `4px`,
    smaller: `8px`,
    small: `12px`,
    regular: `16px`,
    large: `20px`,
    larger: `24px`,
    largest: `36px`,
    xlarge: `40px`,
    xxlarge: `48px`,
  },
});

export const vars = { ...globalTheme, bluePrint };
